const DICTIONARY = [
  {
    tp: "sijelo",
    en: "body",
    color1: "orange",
    color2: "orange",
  },
  {
    tp: "pali",
    en: "activity",
    color1: "yellow",
    color2: "yellow",
  },
  {
    tp: "leko",
    en: "square",
    color1: "pink",
    color2: "green",
  },
  {
    tp: "ike",
    en: "bad",
    color1: "black",
    color2: "black",
  },
  {
    tp: "lawa",
    en: "head",
    color1: "orange",
    color2: "cyan",
  },
  {
    tp: "lanpan",
    en: "catch",
    color1: "yellow",
    color2: "pink",
  },
  {
    tp: "linja",
    en: "long",
    color1: "pink",
    color2: "lime",
  },
  {
    tp: "moli",
    en: "death",
    color1: "black",
    color2: "orange",
  },
  {
    tp: "luka",
    en: "hand",
    color1: "orange",
    color2: "green",
  },
  {
    tp: "open",
    en: "open",
    color1: "yellow",
    color2: "cyan",
  },
  {
    tp: "lipu",
    en: "flat",
    color1: "pink",
    color2: "brown",
  },
  {
    tp: "pini",
    en: "end",
    color1: "black",
    color2: "lime",
  },
  {
    tp: "noka",
    en: "foot",
    color1: "orange",
    color2: "lime",
  },
  {
    tp: "awen",
    en: "stay",
    color1: "yellow",
    color2: "brown",
  },
  {
    tp: "lupa",
    en: "hole",
    color1: "pink",
    color2: "orange",
  },
  {
    tp: "jaki",
    en: "dirty",
    color1: "black",
    color2: "brown",
  },
  {
    tp: "oko",
    en: "eye",
    color1: "orange",
    color2: "black",
  },
  {
    tp: "tawa",
    en: "go",
    color1: "yellow",
    color2: "lime",
  },
  {
    tp: "ko",
    en: "squishy",
    color1: "pink",
    color2: "magenta",
  },
  {
    tp: "utala",
    en: "conflict",
    color1: "black",
    color2: "cyan",
  },
  {
    tp: "nanpa",
    en: "number",
  },
  {
    tp: "kute",
    en: "ear",
    color1: "orange",
    color2: "gray",
  },
  {
    tp: "toki",
    en: "talk",
    color1: "yellow",
    color2: "blue",
  },
  {
    tp: "lili",
    en: "small",
    color1: "pink",
    color2: "black",
  },
  {
    tp: "pakala",
    en: "blunder",
    color1: "black",
    color2: "pink",
  },
  {
    tp: "wan",
    en: "one",
  },
  {
    tp: "uta",
    en: "mouth",
    color1: "orange",
    color2: "pink",
  },
  {
    tp: "pilin",
    en: "feeling",
    color1: "yellow",
    color2: "gray",
  },
  {
    tp: "nasin",
    en: "manner",
    color1: "pink",
    color2: "yellow",
  },
  {
    tp: "nasa",
    en: "silly",
    color1: "black",
    color2: "gray",
  },
  {
    tp: "tu",
    en: "two",
  },
  {
    tp: "nena",
    en: "nose, hill",
    color1: "orange",
    color2: "brown",
  },
  {
    tp: "kama",
    en: "come",
    color1: "yellow",
    color2: "red",
  },
  {
    tp: "poka",
    en: "side",
    color1: "pink",
    color2: "lime",
  },
  {
    tp: "lete",
    en: "cold",
    color1: "black",
    color2: "blue",
  },
  {
    tp: "tonsi",
    en: "nb",
    color1: "orange",
    color2: "magenta",
  },
  {
    tp: "kipisi",
    en: "cut",
    color1: "yellow",
    color2: "black",
  },
  {
    tp: "sewi",
    en: "high",
    color1: "pink",
    color2: "cyan",
  },
  {
    tp: "en",
    en: "and",
  },
  {
    tp: "sinpin",
    en: "front",
    color1: "orange",
    color2: "red",
  },
  {
    tp: "pana",
    en: "give",
    color1: "yellow",
    color2: "magenta",
  },
  {
    tp: "suwi",
    en: "sweet",
    color1: "pink",
    color2: "red",
  },
  {
    tp: "mute",
    en: "many",
    color1: "magenta",
    color2: "magenta",
  },
  {
    tp: "anu",
    en: "or",
  },
  {
    tp: "monsi",
    en: "back",
    color1: "orange",
    color2: "yellow",
  },
  {
    tp: "kepeken",
    en: "use",
    color1: "yellow",
    color2: "green",
  },
  {
    tp: "nimi",
    en: "word",
    color1: "pink",
    color2: "blue",
  },
  {
    tp: "namako",
    en: "extra",
    color1: "magenta",
    color2: "blue",
  },
  {
    tp: "ala",
    en: "not",
  },
  {
    tp: "alasa",
    en: "gather",
    color1: "yellow",
    color2: "orange",
  },
  {
    tp: "epiku",
    en: "epic",
    color1: "magenta",
    color2: "red",
  },
  {
    tp: "telo",
    en: "water",
    color1: "blue",
    color2: "blue",
  },
  {
    tp: "ma",
    en: "land",
    color1: "brown",
    color2: "brown",
  },
  {
    tp: "wawa",
    en: "power",
    color1: "magenta",
    color2: "cyan",
  },
  {
    tp: "taso",
    en: "only, but",
  },
  {
    tp: "mi",
    en: "I, we",
    color1: "blue",
    color2: "yellow",
  },
  {
    tp: "pona",
    en: "good",
    color1: "red",
    color2: "red",
  },
  {
    tp: "tomo",
    en: "house",
    color1: "brown",
    color2: "blue",
  },
  {
    tp: "sin",
    en: "new",
    color1: "magenta",
    color2: "green",
  },
  {
    tp: "seme",
    en: "what",
  },
  {
    tp: "sina",
    en: "you",
    color1: "blue",
    color2: "gray",
  },
  {
    tp: "suli",
    en: "big",
    color1: "red",
    color2: "cyan",
  },
  {
    tp: "esun",
    en: "market",
    color1: "brown",
    color2: "green",
  },
  {
    tp: "ante",
    en: "different",
    color1: "magenta",
    color2: "gray",
  },
  {
    tp: "ona",
    en: "they",
    color1: "blue",
    color2: "magenta",
  },
  {
    tp: "seli",
    en: "hot",
    color1: "red",
    color2: "blue",
  },
  {
    tp: "suno",
    en: "sun, light",
    color1: "brown",
    color2: "yellow",
  },
  {
    tp: "sama",
    en: "same",
    color1: "magenta",
    color2: "black",
  },
  {
    tp: "ni",
    en: "this",
  },
  {
    tp: "jan",
    en: "person",
    color1: "blue",
    color2: "lime",
  },
  {
    tp: "olin",
    en: "love",
    color1: "red",
    color2: "orange",
  },
  {
    tp: "mun",
    en: "moon",
    color1: "brown",
    color2: "gray",
  },
  {
    tp: "kin",
    en: "also",
    color1: "magenta",
    color2: "pink",
  },
  {
    tp: "meli",
    en: "female",
    color1: "blue",
    color2: "red",
  },
  {
    tp: "musi",
    en: "fun",
    color1: "red",
    color2: "gray",
  },
  {
    tp: "tenpo",
    en: "time",
    color1: "brown",
    color2: "cyan",
  },
  {
    tp: "pi",
    en: "of",
  },
  {
    tp: "mije",
    en: "male",
    color1: "blue",
    color2: "black",
  },
  {
    tp: "moku",
    en: "food",
    color1: "red",
    color2: "lime",
  },
  {
    tp: "supa",
    en: "surface",
    color1: "brown",
    color2: "orange",
  },
  {
    tp: "kon",
    en: "air",
    color1: "cyan",
    color2: "cyan",
  },
  {
    tp: "tan",
    en: "from",
  },
  {
    tp: "mama",
    en: "parent",
    color1: "blue",
    color2: "cyan",
  },
  {
    tp: "unpa",
    en: "mate",
    color1: "red",
    color2: "yellow",
  },
  {
    tp: "weka",
    en: "absent",
    color1: "brown",
    color2: "black",
  },
  {
    tp: "lon",
    en: "be, in",
    color1: "cyan",
    color2: "lime",
  },
  {
    tp: "li",
    en: "| verb",
  },
  {
    tp: "kulupu",
    en: "group",
    color1: "blue",
    color2: "brown",
  },
  {
    tp: "kiwen",
    en: "hard",
    color1: "brown",
    color2: "pink",
  },
  {
    tp: "meso",
    en: "medium",
    color1: "cyan",
    color2: "black",
  },
  {
    tp: "e",
    en: "| dir. obj.",
  },
  {
    tp: "kule",
    en: "color",
    color1: "gray",
    color2: "gray",
  },
  {
    tp: "insa",
    en: "inside",
    color1: "cyan",
    color2: "red",
  },
  {
    tp: "la",
    en: "| adverb",
  },
  {
    tp: "kasi",
    en: "plant",
    color1: "lime",
    color2: "lime",
  },
  {
    tp: "jasima",
    en: "mirror",
    color1: "gray",
    color2: "orange",
  },
  {
    tp: "ilo",
    en: "tool",
    color1: "green",
    color2: "green",
  },
  {
    tp: "selo",
    en: "outside",
    color1: "cyan",
    color2: "orange",
  },
  {
    tp: "kili",
    en: "fruit",
    color1: "lime",
    color2: "red",
  },
  {
    tp: "kalama",
    en: "sound",
    color1: "gray",
    color2: "cyan",
  },
  {
    tp: "poki",
    en: "container",
    color1: "green",
    color2: "brown",
  },
  {
    tp: "a",
    en: "ah!",
  },
  {
    tp: "soweli",
    en: "animal",
    color1: "lime",
    color2: "orange",
  },
  {
    tp: "ijo",
    en: "thing",
    color1: "green",
    color2: "blue",
  },
  {
    tp: "o",
    en: "hey!",
  },
  {
    tp: "akesi",
    en: "reptile",
    color1: "lime",
    color2: "green",
  },
  {
    tp: "sona",
    en: "knowledge",
    color1: "gray",
    color2: "yellow",
  },
  {
    tp: "mani",
    en: "money",
    color1: "green",
    color2: "red",
  },
  {
    tp: "anpa",
    en: "bottom",
    color1: "cyan",
    color2: "brown",
  },
  {
    tp: "mu",
    en: "moo",
  },
  {
    tp: "kala",
    en: "fish",
    color1: "lime",
    color2: "blue",
  },
  {
    tp: "ken",
    en: "able",
    color1: "gray",
    color2: "green",
  },
  {
    tp: "misikeke",
    en: "medicine",
    color1: "green",
    color2: "cyan",
  },
  {
    tp: "ale",
    en: "all",
    color1: "cyan",
    color2: "blue",
  },
  {
    tp: "n",
    en: "hmm...",
  },
  {
    tp: "pipi",
    en: "bug",
    color1: "lime",
    color2: "black",
  },
  {
    tp: "jo",
    en: "have",
    color1: "gray",
    color2: "brown",
  },
  {
    tp: "palisa",
    en: "rod",
    color1: "green",
    color2: "lime",
  },
  {
    tp: "waso",
    en: "bird",
    color1: "lime",
    color2: "cyan",
  },
  {
    tp: "lape",
    en: "sleep",
    color1: "gray",
    color2: "magenta",
  },
  {
    tp: "len",
    en: "clothing",
    color1: "green",
    color2: "orange",
  },
  {
    tp: "soko",
    en: "fungus",
    color1: "lime",
    color2: "magenta",
  },
  {
    tp: "wile",
    en: "want",
    color1: "gray",
    color2: "blue",
  },
  {
    tp: "sitelen",
    en: "image",
    color1: "green",
    color2: "gray",
  },
  {
    tp: "pan",
    en: "grain",
    color1: "lime",
    color2: "brown",
  },
  {
    tp: "lukin",
    en: "see",
    color1: "gray",
    color2: "lime",
  },
  {
    tp: "sike",
    en: "circle",
    color1: "green",
    color2: "pink",
  },
  {
    tp: "monsuta",
    en: "fear",
    color1: "gray",
    color2: "black",
  },
];

const COLORS = {
  orange: "#ffa101",
  yellow: "#ffff00",
  pink: "#ff89c3",
  green: "#38761d",
  black: "#000000",
  cyan: "#00ffff",
  lime: "#00ff00",
  brown: "#b45f06",
  magenta: "#ff00ff",
  gray: "#b7b7b7",
  blue: "#0000ff",
  red: "#ff0000",
  white: "#ffffff",
};

const TEXT = `
Every inch of wall space is covered by a bookcase. Each bookcase has six shelves, going almost to the ceiling. Some bookshelves are stacked to the brim with hardback books: science, maths, history, and everything else. Other shelves have two layers of paperback science fiction, with the back layer of books propped up on old tissue boxes or lengths of wood, so that you can see the back layer of books above the books in front. And it still isn't enough. Books are overflowing onto the tables and the sofas and making little heaps under the windows.
`;
